version: 3
extends: "https://api.github.com/repos/medology/Scripts/contents/Pull%20Approve/arepa.pullapprove.yml?ref=master"
pullapprove_conditions:
  - condition: "base.ref == 'master'"
    unmet_status: failure
    explanation: "PullApprove is not configured for this branch"
  - condition: "'[DO NOT REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'[NO REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'No Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'Do Not Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"

